name: sidekick
description: Creates a CLI for your flutter app for custom tasks and automation
version: 0.0.1
repository: https://github.com/phntmxyz/sidekick

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  dartx: ^0.7.1

dev_dependencies:
  lint: ^1.5.0
  path: ^1.8.0
  test: ^1.17.0

executables:
  sidekick: