name: sidekick
description: Creates a CLI for your flutter app for custom tasks and automation
version: 0.0.1
repository: https://github.com/phntmxyz/sidekick

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dartx: ^0.7.1
  mason: ^0.0.1-dev.55

dev_dependencies:
  lint: ^1.5.0
  test: ^1.19.0

executables:
  sidekick: