name: sidekick_core
description: Reusable code pieces for sidekick CLIs
version: 0.3.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  dartx: ^0.7.1
  dcli: ^1.7.1
  yaml: ^3.1.0

dev_dependencies:
  lint: ^1.5.0