name: sidekick_core
description: Reusable code pieces for sidekick CLIs
version: 0.4.0
repository: https://github.com/phntmxyz/sidekick

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  dartx: '>=0.7.1 <2.0.0'
  dcli: ^1.15.0
  yaml: ^3.1.0

dev_dependencies:
  lint: ^1.5.0
  test: ^1.20.0