name: Mason Template Generated

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  code_generation:
    runs-on: ubuntu-latest

    container:
      image: google/dart:2.15

    steps:
      - run: |
         apt-get update
      - uses: actions/checkout@v1
      - name: Install Mason and export path in the Github CI and pull the updated path
        run: |
          dart pub global activate mason_cli
          export PATH=$PATH:$HOME/.pub-cache/bin/
          echo $PATH
          ls -la $HOME/.pub-cache/bin/
          ./sidekick/tool/generateTemplate.sh
          
          git diff --exit-code **/*.g.dart
          