name: sidekick CLI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["2.13", "2.14", "2.15", "dev"]

    container:
      image: google/dart:${{ matrix.version }}

    steps:
      - run: |
         apt-get update
         apt-get install unzip
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: cd sidekick && dart pub get --no-precompile
      - name: Run tests
        run: cd sidekick && dart test

  core_test:
    runs-on: ubuntu-latest

    container:
      image: google/dart:2.15

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: cd sidekick_core && dart pub get --no-precompile
      - name: Run tests
        run: cd sidekick_core && dart test