name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  core_test:
    runs-on: ubuntu-latest

    container:
      image: google/dart:dev

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies sidekick_core
        run: cd sidekick_core && dart pub get --no-precompile
      - name: Install dependencies sidekick_vault
        run: cd sidekick_vault && dart pub get --no-precompile
      - name: Run tests sidekick_core
        run: cd sidekick_core && dart test
      - name: Run tests sidekick_vault
        run: cd sidekick_vault && dart test
  vault_test:
    runs-on: ubuntu-latest

    container:
      image: google/dart:dev

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies sidekick_vault
        run: cd sidekick_vault && dart pub get --no-precompile
      - name: Run tests sidekick_vault
        run: cd sidekick_vault && dart test